python:
  - 'src/spgrep/**'
  - 'tests/**'
  - 'pyproject.toml'
  - 'uv.lock'
  - '.github/workflows/testing.yml'
  - '.github/filters.yaml'
docs:
  - 'docs/**'
  - 'src/spgrep/**'
  - 'pyproject.toml'
  - 'uv.lock'
  - '.github/workflows/testing.yml'
  - '.github/filters.yaml'
