[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=45", "setuptools-scm[toml]>=6.2", "wheel" ]

[project]
name = "spgrep"
description = "On-the-fly generator of space-group irreducible representations"
readme = "README.md"
license = { text = "BSD" }
authors = [
  { name = "Kohei Shinohara", email = "kshinohara0508@gmail.com" },
]
requires-python = ">=3.10.0"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering :: Mathematics",
  "Topic :: Scientific/Engineering :: Physics",
]
dynamic = [
  "version",
]
dependencies = [
  "hsnf>=0.3.16",
  "numpy>=1.20.1",
  "spglib>=2.7",
  "typing-extensions",
]

optional-dependencies.dev = [
  "ipykernel",
  "ipython",
  "matplotlib",
  "nbqa",
  "notebook",
  "phonopy",
  "prek",
  "seaborn",
  "snakeviz",
]
optional-dependencies.docs = [
  "docutils",
  "linkify-it-py",
  "myst-parser",
  "nbsphinx",
  "spgrep[dev]",
  "sphinx",
  "sphinx-autobuild",
  "sphinx-book-theme>=0.8",
  "sphinxcontrib-bibtex>=2.6.2",
]
# Enable version inference
optional-dependencies.testing = [
  "pytest",
  "pytest-cov",
]
urls.homepage = "https://github.com/spglib/spgrep"

[tool.setuptools_scm]

[tool.ruff]
line-length = 99
lint.extend-select = [
  "E", # pycodestyle-errors
  "F", # pyflakes
  "I", # isort
  # "D",           # pydocstyle
  "UP", # pyupgrade
]
lint.extend-ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D203", # Conflict with D211
  "D205",
  "D213", # Conflict with D212
  "E501",
]

[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.mypy]
exclude = [
  'docs',
]
warn_no_return = false
