name: testing

on:
  push:
    branches: [develop, rc]
  pull_request:
    branches: [develop]

env:
  PYTHON_VERSION: "3.12"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        uv sync --extra testing
    - name: Test with pytest
      run: |
        uv run pytest -v --cov=spgrep --cov-report=xml tests/
    - name: Upload coverage to Codecov
      if: matrix.python-version == ${{ env.PYTHON_VERSION }}
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
    - name: Install
      run: |
        uv sync --extra docs
    - name: Build
      run: |
        sphinx-build docs docs_build
    # Generated documents are push to `gh-pages` branch
    # `ACTIONS_DEPLOY_KEY` is set by following: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-ssh-deploy-key
    - name: Deploy
      if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs_build
